const verbList = 
[
    ['arise','arose' ,'arisen' ,'arising','arises'  ],
    ['awake','awoke' ,'awaken' ,'awaking', 'awakes' ],
    ['bear' ,'bore'  ,'born'   ,'bearing', 'bears'  ],
    ['beat' ,'beat'  ,'beaten' ,'beating', 'beats'  ],
    ['become','became','become','becoming', 'becomes' ],
    ['begin','began' ,'begun'  ,'beginning', 'begins'],
    ['bind' ,'bound' ,'bound'  ,'binding', 'binds' ],
    ['bite' ,'bit'   ,'bitten' ,'biting', 'bites'  ],
    ['bleed','bled'  ,'bled'   ,'bleeding', 'bleeds' ],
    ['blow' ,'blew'  ,'blown'  ,'blowing', 'blows'  ],
    ['break','broke' ,'broken' ,'breaking', 'breaks' ],
    ['breed','bred'  ,'bred'   ,'breeding', 'breeds' ],   
    ['bring','brought','brought' ,'bringing', 'brings'],
    ['build','built' ,'built'  ,'building', 'builds' ],
    ['burn' ,'burnt' ,'burnt'  ,'burning', 'burns'  ],
    ['burst','burst' ,'burst'  ,'bursting', 'bursts' ],
    ['buy'  ,'bought','bought' ,'buying', 'buys'   ],
    ['cast' ,'cast'  ,'cast'   ,'casting', 'casts'  ],
    ['catch','caught','caught' ,'catching', 'catches' ],
    ['choose','chose','chosen' ,'choosing', 'chooses' ], 
    ['cling','clung' ,'clung'  ,'clinging', 'clings' ],
    ['come' ,'came'  ,'come'   ,'coming', 'comes'   ],
    ['cost' ,'cost'  ,'cost'   ,'costing', 'costs'  ],
    ['creep','crept' ,'crept'  ,'creeping', 'creeps' ],
    ['cut'  ,'cut'   ,'cut'    ,'cutting', 'cuts'  ],
    ['deal' ,'dealt' ,'dealt'  ,'dealing', 'deals' ],
    ['dig'  ,'dug'   ,'dug'    ,'digging', 'digs'  ],
    ['do'   ,'did'   ,'done'   ,'doing', 'does' ],
    ['draw' ,'drew'  ,'drawn'  ,'drawing', 'draws'  ],
    ['drink','drank' ,'drunk'  ,'drinking', 'drinks' ],
    ['drive','drove' ,'driven' ,'driving', 'drives'  ],
    ['dwell','dwelt' ,'dwelt'  ,'dwelling', 'dwells' ],
    ['eat'  ,'ate'   ,'eaten'  ,'eating', 'eats'   ],
    ['fall' ,'fell'  ,'fallen' ,'falling', 'falls'  ],
    ['feed' ,'fed'   ,'fed'    ,'feeding', 'feeds'  ],
    ['feel' ,'felt'  ,'felt'   ,'feeling', 'feels'  ],
    ['fight','fought','fought' ,'fighting', 'fights' ],
    ['find' ,'found' ,'found'  ,'finding', 'finds'  ],
    ['flee' ,'fled'  ,'fled'   ,'fleeing', 'flees'  ],
    ['fling','flung' ,'flung'  ,'flinging', 'flings' ],
    ['fly'  ,'flew'  ,'flown'  ,'flying', 'flies'],
    ['forbid' ,'forbade','forbidden','forbidding', 'forbids'],
    ['forget' ,'forgot' ,'forgotten','forgetting', 'forgets'],
    ['forgive','forgave','forgiven' ,'forgiving', 'forgives' ],
    ['forsake','forsook','forsaken' ,'forsaking', 'forsakes' ],
    ['freeze' ,'froze'  ,'frozen'   ,'freezing', 'freezes'  ],
    ['get'  ,'got'   ,'got'    ,'getting', 'gets'  ],
    ['give' ,'gave'  ,'given'  ,'giving', 'gives'   ],
    ['go'   ,'went'  ,'gone'   ,'going', 'goes' ],
    ['grind','ground','ground' ,'grinding', 'grinds' ],
    ['grow' ,'grew'  ,'grown'  ,'growing', 'grows'  ],
    ['have' ,'had'   ,'had'    ,'having', 'has'  ],
    ['hear' ,'heard' ,'heard'  ,'hearing', 'hears'  ],
    ['hide' ,'hid'   ,'hidden' ,'hiding', 'hides'   ],
    ['hit'  ,'hit'   ,'hit'    ,'hitting', 'hits'  ],
    ['hold' ,'held'  ,'held'   ,'holding', 'holds'  ],
    ['hurt' ,'hurt'  ,'hurt'   ,'hurting', 'hurts'  ],
    ['keep' ,'kept'  ,'kept'   ,'keeping', 'keeps'  ],
    ['know' ,'knew'  ,'known'  ,'knowing', 'knows'  ],
    ['kneel','knelt' ,'knelt'  ,'kneeling', 'kneels' ],
    ['lay'  ,'laid'  ,'laid'   ,'laying', 'lays'  ],
    ['lead' ,'led'   ,'led'    ,'leading', 'leads'  ], 
    ['learn','learnt','learnt' ,'learning', 'learns' ], 
    ['leave','left'  ,'left'   ,'leaving', 'leaves'  ], 
    ['lend' ,'lent'  ,'lent'   ,'lending', 'lends'  ], 
    ['lie'  ,'lay'   ,'lain'   ,'lying', 'lies'    ],
    ['lose' ,'lost'  ,'lost'   ,'losing' , 'loses' ],
    ['make' ,'made'  ,'made'   ,'making' , 'makes'  ],
    ['mean' ,'meant' ,'meant'  ,'meaning', 'means'  ],
    ['meet' ,'met'   ,'met'    ,'meeting', 'meets'  ],
    ['mistake'  ,'mistook'  ,'mistaken'  ,'mistaking', 'mistakes'  ],
    ['overcome' ,'overcame' ,'overcome'  ,'overcoming', 'overcomes'  ],
    ['overtake' ,'overtook' ,'overtaken' ,'overtaking', 'overtakes'  ],
    ['overthrow','overthrew','overthrown','overthrowing', 'overthrows'],
    ['pay'  ,'paid'  ,'paid'   ,'paying', 'pays'   ],
    ['put'  ,'put'   ,'put'    ,'putting', 'puts'  ],
    ['read' ,'read'  ,'read'   ,'reading', 'reads'  ],
    ['relay','relaid','relaid' ,'relaying', 'relays' ],
    ['rid'  ,'rid'   ,'rid'    ,'ridding', 'rids'  ],
    ['ride' ,'rode'  ,'ridden' ,'riding', 'rides'   ],
    ['ring' ,'rang'  ,'rung'   ,'ringing', 'rings'  ],
    ['rise' ,'rose'  ,'risen'  ,'rising', 'rises'   ],
    ['run'  ,'ran'   ,'run'    ,'running', 'runs'  ],
    ['say'  ,'said'  ,'said'   ,'saying', 'says'   ],
    ['see'  ,'saw'   ,'seen'   ,'seeing', 'sees'   ],
    ['seek' ,'sought','sought' ,'seeking', 'seeks'  ],
    ['sell' ,'sold'  ,'sold'   ,'selling', 'sells'  ],
    ['send' ,'sent'  ,'sent'   ,'sending', 'sends'  ],
    ['set'  ,'set'   ,'set'    ,'setting', 'sets'  ],
    ['shake','shook' ,'shaken' ,'shaking', 'shakes'  ],
    ['shed' ,'shed'  ,'shed'   ,'shedding', 'sheds' ],
    ['shine','shone' ,'shone'  ,'shining', 'shines' ],
    ['shoot','shot'  ,'shot'   ,'shooting', 'shoots' ],
    ['show' ,'showed','shown'  ,'showing', 'shows' ],
    ['shrink','shrank','shrunk','shrinking', 'shrinks'],
    ['shut' ,'shut'   ,'shut'  ,'shutting', 'shuts' ],
    ['sing' ,'sang'  ,'sung'   ,'singing', 'sings' ],
    ['sink' ,'sank'  ,'sunk'   ,'sinking', 'sinks'  ],
    ['sit'  ,'sat'   ,'sat'    ,'sitting', 'sits'  ],
    ['slay' ,'slew'  ,'slain'  ,'slaying', 'slays'  ], 
    ['sleep' ,'slept','slept'  ,'sleeping', 'sleeps' ],
    ['slide','slid'  ,'slid'   ,'sliding', 'slides'  ],
    ['sling','slung' ,'slung'  ,'slinging', 'slings' ],
    ['speak','spoke' ,'spoken' ,'speaking', 'speaks' ],
    ['spend','spent' ,'spent'  ,'spending', 'spends' ],
    ['spin' ,'span'  ,'spun'   ,'spinning', 'spins' ],
    ['spit' ,'spat'  ,'spat'   ,'spitting', 'spits' ],
    ['spread','spread','spread','spreading', 'spreads'],
    ['spring','sprang','sprung','springing', 'springs'],
    ['stand' ,'stood' ,'stood' ,'standing', 'stands' ],
    ['steal' ,'stole' ,'stolen','stealing', 'steals' ],
    ['stick' ,'stuck' ,'stuck' ,'sticking', 'sticks' ],
    ['sting' ,'stung' ,'stung' ,'stinging', 'stings' ],
    ['stride','strode','stridden','striding', 'strides'],
    ['strike','struck','struck','striking', 'strikes' ],
    ['strive','strove','striven','striving', 'strives'],
    ['swear' ,'swore' ,'sworn' ,'swearing', 'swears' ],
    ['sweep' ,'swept' ,'swept' ,'sweeping', 'sweeps' ],
    ['swell' ,'swelled','swollen','swelling', 'swells' ],
    ['swim'  ,'swam'  ,'swum'  ,'swimming', 'swims' ],
    ['swing' ,'swung' ,'swung' ,'swinging', 'swings' ],
    ['take'  ,'took'  ,'taken' ,'taking', 'takes'  ],
    ['tear'  ,'tore'  ,'torn'  ,'tearing ', 'tears' ],
    ['teach' ,'taught','taught','teaching', 'teaches' ],
    ['tell'  ,'told'  ,'told'  ,'telling', 'tells'  ],
    ['think' ,'thought','thought','thinking', 'thinks'],
    ['throw' ,'threw' ,'thrown','throwing', 'throws' ],
    ['thrust','thrust','thrust','thrusting', 'thrusts'],
    ['tread' ,'trod'  ,'trodden','treading', 'treads'], 
    ['understand','understood','understood','understanding', 'understands'],
    ['undo'  ,'undid' ,'undone','undoing', 'undoes'  ],
    ['upset' ,'upset' ,'upset' ,'upsetting', 'upsets'],
    ['wear'  ,'wore'  ,'worn'  ,'wearing', 'wears'  ],
    ['weave' ,'wove'  ,'woven' ,'weaving', 'weaves'  ],
    ['weep'  ,'wept'  ,'wept'  ,'weeping', 'weeps'  ],
    ['win'   ,'won'   ,'won'   ,'winning', 'wins'  ],
    ['wind'  ,'wound' ,'wound' ,'winding', 'winds'  ],
    ['withdraw' ,'withdrew','withdrawn','withdrawing', 'withdraws' ],
    ['withhold' ,'withheld','withheld' ,'withholding', 'withholds' ],
    ['withstand','withstood','withstood','withstanding', 'withstands' ],
    ['wring' ,'wrung' ,'wrung' ,'wringing', 'wrings' ],
    ['write' ,'wrote' ,'written','writing', 'writes' ]
]

export default verbList;